platform :ios, '11.0'

target 'Pose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CoreMLHelpers', :git => 'git://github.com/hollance/CoreMLHelpers'
  pod 'SwiftyBeaver'

end

target 'poseTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

end

target 'poseDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'CoreMLHelpers', :git => 'git://github.com/hollance/CoreMLHelpers'
    
end
