platform :ios, '13.0'

target 'Pose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CoreMLHelpers', :git => 'git://github.com/rdv0011/CoreMLHelpers'
  pod 'SwiftyBeaver', '1.7.0', :inhibit_warnings => true        # https://github.com/SwiftyBeaver/SwiftyBeaver

end

target 'poseTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

end

target 'poseDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'CoreMLHelpers', :git => 'git://github.com/rdv0011/CoreMLHelpers'
    pod 'Zoomy'
    
end
